### PR TITLE
Added footer disclaimer text ("Paid for by...")

### PR DESCRIPTION
**Pull request by bpan**
* Removed the "nav" list because they weren't actually clickable links
* Added semantic classes to divs
* Fixed a typo in _button.scss (No visible change)

### CODE REVIEW

**Comment by bpan** [comment]
Here's how it looks wide and narrow:

disclaimer-wide
disclaimer-narrow

**Comment by Smona** [comment]
@innovativedmm what design did y'all decide on for this?

**Comment by bpan** [comment]
Here's how it looks:

disclaimer-wide

disclaimer-narrow

@amanda I can make another pull request with the social icons at the top so you can compare. It seems like it will be crowded up there, but I can give it a try.

**Comment by innovativedmm** [comment]
Love the first one...

**Comment by Smona** [comment]
@innovativedmm @bpan I'm gonna make a compromise between the previous and the new arrangement

**Pull request merged**
